--- #YAML:1.0
name: CPAN-WWW-Testers-Generator
version: 0.21
author:
  - Leon Brocard <leon@astray.com>
abstract: Download and summarize CPAN Testers data
license: perl
requires:
  DBD::SQLite: 0
  DateTime: 0
  Email::Simple: 0
  Mail::Address: 0
  Net::NNTP: 0
  Test::More: 0
  version: 0
provides:
  CPAN::WWW::Testers::Generator:
    file: lib/CPAN/WWW/Testers/Generator.pm
    version: 0.21
generated_by: Module::Build version 0.24
