--- #YAML:1.0
name:                     CPAN-WWW-Testers-Generator
version:                  0.31
abstract:                 The pre-2009 CPAN Testers data manager codebase
author:
  - Barbie <barbie@cpan.org>
  - Leon Brocard <leon@astray.com>

license:                  perl
distribution_type:        module
installdirs:              site

requires:
  perl:                   5.006
recommends:
  Test::More:             0.70
  Test::Pod:              1.00
  Test::Pod::Coverage:    0.08
  Test::CPAN::Meta:       0.12
build_requires:
  Test::More:             0.70

provides:
  CPAN::WWW::Testers::Generator:
    file:     lib/CPAN/WWW/Testers/Generator.pm
    version:  0.31

no_index:
  directory:
    - t

resources:
  license:    http://dev.perl.org/licenses/
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=-CPAN-WWW-Testers-Generator

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0
